"""Build the V16 rehearsal pack from the compiled V16 deck and its notes.

Same method as build_rehearsal_script_v7.py: the "On slide" text is the
projected page, the "Say" text is the frame's note with number macros expanded
from deck_numbers_v16.tex.  Writes reports/rehearsal_pack_v16.md and refreshes
reports/rehearsal_pack_v1.md (the stable rehearsal-script path) so its slide
numbering matches the V16 deck.  Refuses to write if an internal label from the
V16 verifier's list appears in the pack.
"""
from pathlib import Path
import re
import sys

import pymupdf
import pypandoc

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))
import verify_deck_r6 as gates  # noqa: E402

source = (HERE / "JMP_seminar_beamer_v16.tex").read_text(encoding="utf-8")
numbers = (HERE / "deck_numbers_v16.tex").read_text(encoding="utf-8")
macros = {name: value.replace("$-$", "\u2212")
          for name, value in re.findall(r"\\newcommand\{\\(\w+)\}\{(.*)\}", numbers)}
macros.update(EA="EA", ATT="ATT")


def expand(text: str) -> str:
    for name, value in sorted(macros.items(), key=lambda item: -len(item[0])):
        text = re.sub(r"\\" + re.escape(name) + r"(\{\})?(?![A-Za-z])", lambda _: value, text)
    return text


def spoken(latex: str) -> str:
    return pypandoc.convert_text(expand(re.sub(r"\s+", " ", latex).strip()), "markdown",
                                 format="latex", extra_args=["--wrap=none"]).strip()


frames = re.findall(r"\\begin\{frame\}.*?\\end\{frame\}", source, re.S)
document = pymupdf.open(HERE / "build/JMP_seminar_beamer_v16.pdf")
if len(frames) != len(document):
    raise SystemExit(f"frame/page mismatch: {len(frames)} vs {len(document)}")

out = [
    "# Seminar rehearsal script — V16", "",
    f"The presentation contains {len(frames)} slides and no backup appendix. "
    "Slide numbers match JMP_seminar_beamer_v16.pdf. Content is drawn from the V15 "
    "research-story report and results gallery.", "",
    "EA is presented first, as the opportunity-prospect perspective; ATT is the "
    "attained-bundle benchmark. That is an order of presentation: neither perspective "
    "is designated primary.", "",
]
for index, (frame, page) in enumerate(zip(frames, document), 1):
    projected = re.sub(r"\s+", " ", page.get_text()).strip()
    projected = re.sub(r"[\x00-\x1f\x7f-\x9f]", "", projected)
    note = re.search(r"\\note\{(.*?)\}\s*\\end\{frame\}", frame, re.S)
    if not note:
        raise SystemExit("missing note on frame " + str(index))
    out += [f"## Slide {index}", "", "On slide: " + projected, "", "Say: " + spoken(note[1]), ""]

qa = [
    ("Is the ex-ante measure your preferred welfare measure?",
     r"No. The two measures answer different welfare questions. EA is shown first because "
     r"this talk is about opportunities; ATT is the attained-bundle benchmark. Choosing "
     r"between them is a substantive normative decision that the paper does not make."),
    ("Are these causal shares of inequality due to unequal opportunities?",
     r"No. They are restricted structural accounting shares. Household resources, needs "
     r"and composition are held fixed, access is local access rather than total "
     r"opportunity, identification rests on maintained restrictions, and parameter "
     r"uncertainty has not been propagated."),
    ("Why does equivalisation matter so much for couples under EA?",
     r"Dividing by the modified-OECD scale moves the ex-ante access-plus-earnings share "
     r"from \VEACoupOppRaw{}\% to \VEACoupOppEq{}\% of baseline inequality and moves the "
     r"preference contribution from \VEACoupPrefRaw{} to \VEACoupPrefEq{} Gini points. "
     r"That is why both scales are always reported and no directional claim about "
     r"preferences is made."),
    ("Why do single adults reverse and couples not?",
     r"It is not tested. One reading is that a single adult's participation depends on one "
     r"earner's access, while a couple's joint budget and second earner leave earning "
     r"opportunities in front. The reversal is a finding for single-adult households only."),
    ("Does the preference channel measure what households are responsible for?",
     r"No. It is systematic utility heterogeneity, including a reduced-form child-related "
     r"time-constraint shifter. Equating it with responsibility would be a normative step "
     r"the paper does not take."),
]
out += ["## Extended Q&A", ""]
for question, answer in qa:
    out += [f"### {question}", "", spoken(answer), ""]
out += ["<!-- Generated by beamer/build_rehearsal_script_v16.py from "
        "beamer/JMP_seminar_beamer_v16.tex and build/JMP_seminar_beamer_v16.pdf. -->", ""]
payload = "\n".join(out)

hits = []
for pattern, case_sensitive in gates.V16_INTERNAL:
    found = re.search(pattern, payload, 0 if case_sensitive else re.I)
    if found and "Own-set equal-consumption" not in payload[max(0, found.start() - 900):found.start()]:
        hits.append(found.group(0))
if hits:
    raise SystemExit("REFUSED: internal labels in rehearsal pack: " + ", ".join(hits))

for target in (ROOT / "reports/rehearsal_pack_v16.md", ROOT / "reports/rehearsal_pack_v1.md"):
    target.write_text(payload, encoding="utf-8", newline="\n")
print(f"Rehearsal script: {len(frames)} slides -> reports/rehearsal_pack_v16.md and rehearsal_pack_v1.md")
