#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate every numeral the R6 seminar deck is allowed to state.

R6 (JMP_W1_fork_ruling_v1.md Appendix A) and the BASELINE-F-1 ruling
(JMP_W1_BASELINE_F1_authorization_and_Cobs_ruling_v1.md) bound what may be
shown.  This script reads ONLY the three authorized sources:

  S11  MNL/experiments/JMP_SEMINAR_SPRINT/runs/s11_welfare_specs_of_record/
       s11_{singles,couples}_parameter_table_v1.csv  -- model of record
  FIT  MNL_posfit/outputs/positive_fit_diagnostics_v2/                 -- G2 gate
  W1F  MNL/outputs/welfare/baseline_f1_v1/                             -- E1 baseline

and writes deck_numbers_r6.tex plus build/r6_number_provenance.json.

It refuses to emit a fit statistic whose G2 label is not ADEQUATE, and it
refuses to emit any W1-EA quantity: no source here contains one.
"""
from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]                       # C:\Users\hisham\Repo
MNL = REPO / "MNL"
POSFIT = REPO / "MNL_posfit" / "outputs" / "positive_fit_diagnostics_v2"
S11 = MNL / "experiments" / "JMP_SEMINAR_SPRINT" / "runs" / "s11_welfare_specs_of_record"
W1F = MNL / "outputs" / "welfare" / "baseline_f1_v1"

OUT_TEX = HERE / "deck_numbers_r6.tex"
OUT_JSON = HERE / "build" / "r6_number_provenance.json"

# Fit statistics the deck may state.  R6 build brief: extensive accuracy only,
# and only where the G2 quadrature gate labels it ADEQUATE.
ALLOWED_FIT_STATISTIC = "extensive_accuracy"


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def rows(p: Path) -> list[dict]:
    with p.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


# --------------------------------------------------------------------------
# number formatting: the deck's display precision, fixed here, never on a slide
# --------------------------------------------------------------------------
def eur(x: float) -> str:
    """Household EUR/month, unequivalised: nearest euro, thin-space thousands."""
    return "{:,}".format(int(round(x))).replace(",", r"\,")


def gini(x: float) -> str:
    return "%.3f" % x


def pct1(x: float) -> str:
    return "%.1f" % (100.0 * x)


def num(x: float, d: int) -> str:
    return ("%." + str(d) + "f") % x


def count(n: int) -> str:
    return "{:,}".format(int(n)).replace(",", r"\,")


def main() -> int:
    prov: dict = {"sources": {}, "macros": {}, "refusals": []}
    tex: list[str] = [
        "% deck_numbers_r6.tex -- GENERATED by make_deck_numbers_r6.py.",
        "% Do not edit by hand.  Every numeral on an R6 slide comes from here.",
        "% Sources: S11 parameter tables (model of record);",
        "%          positive_fit_diagnostics_v2 (G2-ADEQUATE statistics only);",
        "%          welfare/baseline_f1_v1 (BASELINE-F-1, commit 6048c9f, verified b5550af).",
        "",
    ]

    def mac(name: str, value: str, source: str, raw=None) -> None:
        tex.append(r"\newcommand{\%s}{%s}" % (name, value))
        prov["macros"][name] = {"rendered": value, "source": source, "raw": raw}

    # ---------------------------------------------------------------- W1-F
    agg_path = W1F / "baseline_f1_full_sample_aggregates_v1.json"
    agg = json.loads(agg_path.read_text(encoding="utf-8"))
    prov["sources"]["baseline_f1_full_sample_aggregates_v1.json"] = {
        "path": str(agg_path), "sha256": sha256(agg_path),
        "executed_commit": agg["executed_commit"],
        "recorded_commit": "6048c9f7", "verified_commit": "b5550af5",
        "units": agg["units"], "weight": agg["weight"], "pooled_row": agg["pooled_row"],
        "C_obs_benchmark": agg["C_obs_benchmark"],
    }
    if agg["pooled_row"]:
        raise SystemExit("REFUSED: aggregates carry a pooled row; R6 forbids a pooled figure")
    if agg["C_obs_benchmark"] != "NOT PRODUCED":
        prov["refusals"].append(
            "C_obs benchmark present in source but E3 is not authorised; not emitted")

    tex.append("% --- BASELINE-F-1 (E1): household EUR/month, unequivalised, dwt-weighted ---")
    for grp, tag in (("singles", "Sing"), ("couples", "Coup")):
        s = agg["samples"][grp]
        src = "baseline_f1_full_sample_aggregates_v1.json samples.%s" % grp
        mac("WF" + tag + "N", count(s["unweighted_n"]), src, s["unweighted_n"])
        mac("WF" + tag + "Mean", eur(s["dwt_weighted_mean"]), src, s["dwt_weighted_mean"])
        mac("WF" + tag + "Median", eur(s["dwt_weighted_median"]), src, s["dwt_weighted_median"])
        mac("WF" + tag + "Gini", gini(s["dwt_weighted_gini"]), src, s["dwt_weighted_gini"])
        mac("WF" + tag + "Workers", count(s["worker_count"]), src, s["worker_count"])
        mac("WF" + tag + "Nonworkers", count(s["nonworker_count"]), src, s["nonworker_count"])
        c = agg["checks"][grp]
        mac("WF" + tag + "Cone", "%g" % c["C1"]["max_abs_W_minus_C_obs"],
            src.replace("samples", "checks") + " C1", c["C1"]["max_abs_W_minus_C_obs"])
        mac("WF" + tag + "Ctwo", count(c["C2"]["invalid_ratio_count"]),
            src.replace("samples", "checks") + " C2", c["C2"]["invalid_ratio_count"])
        mac("WF" + tag + "Cfive", "%.1e" % c["C5"]["max_abs_utility_difference"],
            src.replace("samples", "checks") + " C5",
            c["C5"]["max_abs_utility_difference"])
    tex.append("")

    # ------------------------------------------------------------- fit / G2
    g2_path = POSFIT / "g2_adequacy.csv"
    g2 = rows(g2_path)
    prov["sources"]["g2_adequacy.csv"] = {"path": str(g2_path), "sha256": sha256(g2_path)}

    hc_path = POSFIT / "hard_classification_metrics.csv"
    prov["sources"]["hard_classification_metrics.csv"] = {
        "path": str(hc_path), "sha256": sha256(hc_path)}

    tex.append("% --- positive fit: ONLY G2-ADEQUATE statistics (weighted, the binding rule) ---")
    tag_of = {"singles_male": "SM", "singles_female": "SF",
              "couples_male": "CM", "couples_female": "CF"}
    adequate_groups: list[str] = []
    limited_groups: list[str] = []
    for r in g2:
        if r["weighting"] != "weighted" or r["statistic"] != ALLOWED_FIT_STATISTIC:
            continue
        grp = r["group"]
        if r["label"] != "ADEQUATE":
            limited_groups.append(grp)
            prov["refusals"].append(
                "%s %s is %s (ratio %s); not emitted"
                % (grp, ALLOWED_FIT_STATISTIC, r["label"], r["adequacy_ratio_mcse_to_sampling_sd"]))
            continue
        adequate_groups.append(grp)
        v = float(r["node_bootstrap_mean"])
        mac("FitExt" + tag_of[grp], pct1(v),
            "g2_adequacy.csv %s/weighted/%s ADEQUATE" % (grp, ALLOWED_FIT_STATISTIC), v)
        mac("FitExtRatio" + tag_of[grp], num(float(r["adequacy_ratio_mcse_to_sampling_sd"]), 2),
            "g2_adequacy.csv %s/weighted/%s adequacy ratio" % (grp, ALLOWED_FIT_STATISTIC),
            float(r["adequacy_ratio_mcse_to_sampling_sd"]))
    mac("FitAdequateCount", str(len(adequate_groups)), "g2_adequacy.csv count of ADEQUATE groups")
    mac("FitLimitedCount", str(len(limited_groups)), "g2_adequacy.csv count of limited groups")
    tex.append("")

    provp = POSFIT / "run_provenance.json"
    pf = json.loads(provp.read_text(encoding="utf-8"))
    prov["sources"]["run_provenance.json"] = {"path": str(provp), "sha256": sha256(provp)}
    tex.append("% --- S11 objectives reproduced by the diagnostics evaluator ---")
    mac("ObjSingles", num(pf["objective_values"]["singles"], 3),
        "run_provenance.json objective_values.singles", pf["objective_values"]["singles"])
    mac("ObjCouples", num(pf["objective_values"]["couples"], 3),
        "run_provenance.json objective_values.couples", pf["objective_values"]["couples"])
    mac("FitNodes", str(pf["predictive_support"]["full_nodes"]),
        "run_provenance.json predictive_support.full_nodes")
    mac("FitSims", str(pf["simulation"]["outcome_vectors"]),
        "run_provenance.json simulation.outcome_vectors")
    mac("FitBootReps", str(pf["node_bootstrap"]["replicates"]),
        "run_provenance.json node_bootstrap.replicates")
    mac("EvaluatorCommit", pf["evaluator_commit"][:7],
        "run_provenance.json evaluator_commit")
    tex.append("")

    # -------------------------------------------------------- S11 estimates
    tex.append("% --- S11 model of record: estimated opportunity kernel ---")
    for grp, tag, fn in (("singles", "Sing", "s11_singles_parameter_table_v1.csv"),
                         ("couples", "Coup", "s11_couples_parameter_table_v1.csv")):
        p = S11 / fn
        prov["sources"][fn] = {"path": str(p), "sha256": sha256(p)}
        tab = {r["param"]: r for r in rows(p)}
        active = [r for r in tab.values() if r["pinned"] == "False"]
        mac("S%sParams" % tag, str(len(tab)), "%s row count" % fn, len(tab))
        mac("S%sActive" % tag, str(len(active)), "%s non-pinned rows" % fn, len(active))
        if grp == "singles":
            for nm, label in (("beta_E", "AccessConst"), ("beta_E_gsur", "AccessSur"),
                              ("beta_h_f35", "HoursFThirtyFive"), ("beta_c", "BetaC"),
                              ("sigma", "WageSigma"), ("beta_w_educH", "WageEducH"),
                              ("beta_w_pexp", "WagePexp")):
                r = tab[nm]
                mac("SEleven" + label, num(float(r["estimate"]), 3),
                    "%s %s estimate" % (fn, nm), float(r["estimate"]))
                if r["se_robust_CR1"]:
                    mac("SEleven" + label + "Z", num(float(r["z_robust"]), 1),
                        "%s %s z_robust" % (fn, nm), float(r["z_robust"]))
    tex.append("")

    # ------------------------------------------------------- sample framing
    tex.append("% --- estimation frames (S11 corrected criterion-A) ---")
    mac("FrameSingles", count(agg["samples"]["singles"]["unweighted_n"]),
        "baseline_f1 samples.singles.unweighted_n")
    mac("FrameCouples", count(agg["samples"]["couples"]["unweighted_n"]),
        "baseline_f1 samples.couples.unweighted_n")
    tex.append("")

    OUT_JSON.parent.mkdir(exist_ok=True)
    OUT_TEX.write_text("\n".join(tex) + "\n", encoding="utf-8")
    OUT_JSON.write_text(json.dumps(prov, indent=2, sort_keys=True), encoding="utf-8")
    print("wrote %s (%d macros)" % (OUT_TEX.name, len(prov["macros"])))
    print("G2-ADEQUATE extensive accuracy: %s" % (", ".join(adequate_groups) or "none"))
    print("withheld as quadrature-limited: %s" % (", ".join(limited_groups) or "none"))
    for r in prov["refusals"]:
        print("  refused: %s" % r)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
