"""Create the editable R7 deck sources from the frozen R6 predecessor."""
from pathlib import Path
import hashlib
import re


HERE = Path(__file__).resolve().parent
source = (HERE / "JMP_seminar_deck_r6.tex").read_text(encoding="utf-8")
source = source.replace("r6", "r7").replace("R6", "R7")
source = source.replace(
    "% R2 retires every slide, figure, number and note built on W1-EA.  None of\n"
    "% that material is carried here, repaired here, or restated here; the v4.1\n"
    "% deck keeps it as a historical artifact and is not built for this seminar.",
    "% The distinct ex-ante opportunity-prospect metric is definition-only and\n"
    "% numerically blocked; no numerical result for it is present in this deck.")
source = source.replace("POSFIT v3", "POSFIT v3b")
source = source.replace("positive_fit_diagnostics_v3", "positive_fit_diagnostics_v3b")
source = source.replace("commit 96693269", "commit cd7247cf")
source = source.replace(
    "The money metric is derived from the\nMeasure-1 reference-set principle. Under the current empirical specification\n"
    "its direct reference collapses to the universally available non-employment\n"
    "state; opportunity heterogeneity therefore affects the current welfare\nmeasure through attained bundles.",
    "The empirical Mapping-F implementation evaluates the attained bundle\n"
    "against the universally available non-employment reference. Under the\n"
    "current specification, estimated opportunity density therefore affects this\n"
    "money metric through attained outcomes rather than through a direct\n"
    "opportunity-prospect term.")

slide8 = r'''\begin{frame}
\headlineframe{Extensive accuracy is reportable for women in each sample;
both groups of men are withheld.}
\slidefig{fitext_r7}
\caveat{The preregistered weighted numerical-adequacy threshold is unchanged.
Single men and coupled men are quadrature-limited; their extensive accuracy is
not reported.}
\note{POSFIT v3b fully re-evaluates the current estimates after rebuilding the
structural band indicators on the priced nodes. The numerical-adequacy rule is
applied mechanically at the unchanged threshold. Single women and coupled
women clear it. Single men and coupled men are quadrature-limited, so their
extensive accuracy is withheld. On the weighted composite decision rule,
conditioning is mechanical stochastic conditioning in all four groups. The
excess-dispersion adjudication is misspecification evidence for the two couple
groups and inconclusive/quadrature-limited for the two single groups. The
earlier three-group excess-predictability claim is withdrawn.}
\end{frame}'''

slide9 = r'''\begin{frame}
\headlineframe{The remaining common hours mismatch is the observed 37-hour
mass point, outside structural FT.}
\slidefig{hours37_r7}
\caveat{Underprediction of the observed 37-hour mass point is
\FitGapThirtySevenMinVSeven--\FitGapThirtySevenMaxVSeven{} percentage points
across groups; this is not a structural full-time-band claim.}
\note{The corrected structural bands use the current model definitions. The
observed 37-hour point is isolated as a separate descriptive residual cell,
outside the structural full-time band. Its observed-minus-predicted gap ranges
from \FitGapThirtySevenMinVSeven{} to \FitGapThirtySevenMaxVSeven{} percentage
points. The population MAE is \FitMAESinglesVSeven{} for singles and
\FitMAECouplesVSeven{} for couples. Singles MAE rises slightly, so the correction
is not described as an across-the-board fit improvement. The benchmark audit
also found a RUM-A input-width defect: its alternative-invariant log-density
shift cancels from the conditional likelihood, and RUM-B does not read those
rows, but absolute RUM-A opportunity-mass metadata remain a disclosed
limitation.}
\end{frame}'''

matches = list(re.finditer(r"\\begin\{frame\}.*?\\end\{frame\}", source, re.S))
if len(matches) < 9:
    raise SystemExit("deck frame parse failed")
for index, replacement in ((8, slide9), (7, slide8)):
    match = matches[index]
    source = source[:match.start()] + replacement + source[match.end():]
source = source.replace(
    r"coupled men   & \FitExtCM{}\% & reported (ratio \FitExtRatioCM{}) \\",
    r"coupled men   & ---           & quadrature-limited, withheld \\")
source = source.replace(
    "single men    & ---           & quadrature-limited, withheld \\",
    "single men    & ---           & quadrature-limited, withheld \\")

decomp_sentence = (
    "This percentage is the change generated by the declared restricted P/A/B "
    "game. It is not an estimate of the total fraction of inequality caused by "
    "unequal job opportunities.")
source = source.replace(
    "conventions. The preference contribution is not sign-robust to\n"
    "equivalisation.\\par}",
    "conventions. The preference contribution is not sign-robust to\n"
    "equivalisation. " + decomp_sentence + "\\par}", 1)
short_hours = (
    "The preliminary attainment exercise is evaluated on the already-priced "
    "estimation panel. That panel sparsely represents the lower part of the "
    "structural hours support. A separate integration audit shows substantial "
    "structural mass in that region. The direct importance of this limitation "
    "for the current attained-bundle decomposition has not been fully quantified, "
    "so the result remains explicitly preliminary.")
source = source.replace(
    "does not contain that counterfactual.}",
    "does not contain that counterfactual. " + decomp_sentence + " " + short_hours + "}", 1)

run_prov = (HERE.parent.parent / "MNL_posfit/outputs/positive_fit_diagnostics_v3b/"
            "run_provenance.json")
sha = hashlib.sha256(run_prov.read_bytes()).hexdigest().upper()
source = re.sub(
    r"% [A-F0-9]{64}\.\n% Bounded decomposition:",
    "% " + sha + ".\n% Bounded decomposition:", source, count=1)
source = source.replace(
    "% Presentation: REPORT-V7; all decomposition frames after appendix.",
    "% Presentation: REPORT-V7; corrected fit slides 8--9; decomposition retained in backup.")

(HERE / "JMP_seminar_deck_r7.tex").write_text(source, encoding="utf-8")
(HERE / "JMP_seminar_deck_r7_rehearsal.tex").write_text(
    "% Second-screen rehearsal build of the R7 deck: same source, notes on the right.\n"
    "\\def\\RehearsalDeck{}\n\\input{JMP_seminar_deck_r7}\n",
    encoding="utf-8")
print("wrote JMP_seminar_deck_r7.tex and rehearsal driver")
