"""Release checks for the R7 deck and its corrected fit slides."""
from pathlib import Path
import json
import re
import subprocess


HERE = Path(__file__).resolve().parent
source = (HERE / "JMP_seminar_deck_r7.tex").read_text(encoding="utf-8")
numbers = (HERE / "deck_numbers_r7.tex").read_text(encoding="utf-8")
pdf = HERE / "build/JMP_seminar_deck_r7.pdf"
text_path = HERE / "build/JMP_seminar_deck_r7_text.txt"
if not text_path.exists():
    subprocess.run([str(Path.home() / "AppData/Local/Programs/MiKTeX/miktex/bin/x64/pdftotext.exe"),
                    "-layout", str(pdf), str(text_path)], check=True)
rendered = text_path.read_text(encoding="utf-8", errors="replace")
provenance = json.loads((HERE / "build/r7_number_provenance.json").read_text(encoding="utf-8"))

frames = list(re.finditer(r"\\begin\{frame\}.*?\\end\{frame\}", source, re.S))
slide8 = frames[7].group(0) if len(frames) >= 9 else ""
slide9 = frames[8].group(0) if len(frames) >= 9 else ""
slide8_flat = re.sub(r"\s+", " ", slide8)
slide9_flat = re.sub(r"\s+", " ", slide9)
source_flat = re.sub(r"\s+", " ", source)
checks = {
    "pdf_present": pdf.exists() and pdf.stat().st_size > 100_000,
    "slide8_withholds_both_men": all(value in slide8_flat for value in (
        "both groups of men are withheld", "Single men and coupled men",
        "three-group excess-predictability claim is withdrawn")),
    "slide8_four_group_adjudication": all(value in slide8_flat for value in (
        "mechanical stochastic conditioning in all four groups",
        "misspecification evidence for the two couple groups",
        "inconclusive/quadrature-limited for the two single groups")),
    "slide9_37_hour_finding": all(value in slide9_flat for value in (
        "observed 37-hour", "outside structural FT",
        "not a structural full-time-band claim", "Singles MAE rises slightly")),
    "corrected_posfit_source": (
        "outputs/positive_fit_diagnostics_v3b" in
        provenance["sources"]["g2_adequacy.csv"]["path"].replace("\\", "/")
        and "cd7247cf" in numbers),
    "only_female_accuracy_macros": (
        "\\FitExtSF" in numbers and "\\FitExtCF" in numbers
        and "\\FitExtSM" not in numbers and "\\FitExtCM{" not in numbers),
    "v7_assets": all((HERE / "figures/r7" / name).exists() for name in (
        "fitext_r7_slide.pdf", "hours37_r7_slide.pdf",
        "calibration_r7_slide.pdf", "r7_source_manifest.json")),
    "w1_wording": all(value in source_flat for value in (
        "The empirical Mapping-F implementation evaluates the attained bundle",
        "rather than through a direct opportunity-prospect term")),
    "decomp_caveat": (
        "This percentage is the change generated by the declared restricted P/A/B game. "
        "It is not an estimate of the total fraction of inequality caused by unequal job opportunities."
        in source.replace("\n", " ")),
    "no_retired_fit_claims": not re.search(
        r"near[- ]full[- ]time|9\\.48|7\\.21|9\\.5 percentage|coupled men pass",
        source + rendered, re.I),
    "no_cross_estimand_wording": not re.search(
        r"flat consumption|integrates over the opportunity distribution|own opportunity distribution|ex-ante value|W1-EA",
        source + rendered, re.I),
}
for name, status in checks.items():
    print(("PASS" if status else "FAIL") + ": " + name)
failed = [name for name, status in checks.items() if not status]
if failed:
    raise SystemExit("deck R7 failed: " + ", ".join(failed))
