"""REPORT-V7 sections implementing the two accepted pre-seminar rulings.

The quantitative decomposition evidence is inherited from v5/v6.  Predictive
fit prose is replaced with the corrected POSFIT-v3b and Band-Fix-2 verdicts.
No estimator, pricing routine or W_EA_flat numerical routine is called here.
"""
import re

from v6_sections import *  # noqa: F403 -- inherit unaffected v6 prose
import v5_sections as evidence
import v6_sections as v6


DECOMP_CAVEAT = (
    'This percentage is the change generated by the declared restricted P/A/B '
    'game. It is not an estimate of the total fraction of inequality caused by '
    'unequal job opportunities.')
SHORT_HOURS_LIMITATION = (
    'The preliminary attainment exercise is evaluated on the already-priced '
    'estimation panel. That panel sparsely represents the lower part of the '
    'structural hours support. A separate integration audit shows substantial '
    'structural mass in that region. The direct importance of this limitation '
    'for the current attained-bundle decomposition has not been fully quantified, '
    'so the result remains explicitly preliminary.')
W1_WORDING = (
    'The empirical Mapping-F implementation evaluates the attained bundle '
    'against the universally available non-employment reference. Under the '
    'current specification, estimated opportunity density therefore affects '
    'this money metric through attained outcomes rather than through a direct '
    'opportunity-prospect term.')
WEA_STATUS = r'''$W_{EA,\mathrm{flat}}$ is a distinct ex-ante opportunity-prospect metric. Its definition is fixed but it has no numerical result. Write its eventual flat-reference inversion as $H_i^{\mathrm{reference}}(m)=J_i^{\mathrm{actual}}$. The primary H-F domain retains the full opportunity environment: states with $C\leq0$ contribute zero to $J_i^{\mathrm{actual}}$ through the $C\rightarrow0^+$ utility limit, while the reference retains those states and assigns the common consumption $m$. H-D is an estimated-domain sensitivity and H-X is a disclosed sample-restriction sensitivity. No one-euro floor, observed-consumption substitution or silent household deletion is permitted. The 260 couples lacking a priced NN state and the associated support/pricing requirements currently block numerical implementation; the first post-seminar numerical task is exact-H pre-validation before any minimum accepted pricing design is launched.'''


def replace_paragraph(text, prefix, replacement):
    paragraphs = text.split('\n\n')
    hits = [i for i, paragraph in enumerate(paragraphs)
            if paragraph.lstrip().startswith(prefix)]
    if len(hits) != 1:
        raise RuntimeError('Expected one paragraph starting with: ' + prefix)
    paragraphs[hits[0]] = replacement
    return '\n\n'.join(paragraphs)


def clean_w1(text):
    text = text.replace('equivalent flat consumption level',
                        'equivalent consumption at the non-employment reference state')
    text = text.replace(
        'Their references fix a wage or an unearned-income intercept and maximize '
        'over a deterministic budget set. Ours fixes consumption across the '
        'alternatives of an estimated opportunity distribution and integrates. '
        'That is a different reference and, as Section 6 records, the ordering is '
        'sensitive to it.',
        'Their references fix a wage or an unearned-income intercept and maximize '
        'over a deterministic budget set. ' + W1_WORDING)
    return text


def attach_decomp_caveat(text):
    pattern = (r'(Within that bounded game, equalising P/A/B changes the Gini by '
               r'.*?depending on sample and reporting scale\.)')
    text, count = re.subn(pattern, r'\1\n\n' + DECOMP_CAVEAT, text, count=1)
    if count != 1:
        raise RuntimeError('Could not attach the required DECOMP-2 caveat')
    return text


ABSTRACT = r'''We study how unequal job opportunities contribute to inequality in money-metric well-being. The verified current measure is the Mapping-F attained-bundle money metric: the attained bundle is evaluated against the universally available non-employment reference, so estimated opportunity density affects the measure through attained outcomes rather than through a direct opportunity-prospect term. We model labour supply as a choice among latent jobs on French EU-SILC data, with EUROMOD computing taxes, benefits and disposable income at every alternative work arrangement. Preferences and opportunity components are jointly estimated under maintained functional-form and exclusion restrictions. We implement a preliminary restricted structural decomposition of the attained-bundle money metric, equalising systematic utility heterogeneity, coarse geographic/temporal access heterogeneity and earning opportunities while holding household resources, needs and composition fixed. Within this restricted game, the earning-opportunity channel has a larger Shapley contribution than the coarse geographic/temporal access channel. The exercise is preliminary and is not interpreted as the total share of well-being inequality due to opportunities.'''

PRELIM_NOTE = (
    'Discussion draft. Corrected POSFIT-v3b predictive evidence and the verified '
    'Mapping-F results are reported with the preliminary restricted P/A/B '
    'decomposition in the main text; Appendix D retains its full technical record. '
    'The distinct ex-ante opportunity-prospect metric is defined but numerically blocked.')

INTRO = clean_w1(v6.INTRO)
INTRO = replace_paragraph(
    INTRO, 'A separately defined ex-ante metric is being reconstructed', WEA_STATUS)
INTRO = replace_paragraph(
    INTRO, 'The computed preliminary restricted-operator decomposition',
    'We implement a preliminary restricted structural decomposition of the '
    'attained-bundle money metric, equalising systematic utility heterogeneity, '
    'coarse geographic/temporal access heterogeneity and earning opportunities '
    'while holding household resources, needs and composition fixed. Within this '
    'restricted game, the earning-opportunity channel has a larger Shapley '
    'contribution than the coarse geographic/temporal access channel. The exercise '
    'is preliminary and is not interpreted as the total share of well-being '
    'inequality due to opportunities; Section 5 reports it and Appendix D retains '
    'the full technical presentation.')

WELFARE = clean_w1(v6.WELFARE)
WELFARE = replace_paragraph(
    WELFARE, 'The money metric is derived from the own-set equal-consumption principle.',
    W1_WORDING)
WELFARE += ('\n\n## The distinct ex-ante opportunity-prospect metric\n\n'
            + WEA_STATUS + '\n')

RESULTS = v6.RESULTS
RESULTS = replace_paragraph(
    RESULTS, 'Aggregate participation and occupation margins are reproduced',
    'Population participation and occupation margins remain close in aggregate, '
    'while the corrected hours comparison is uneven. The corrected individual-level '
    'diagnostics are adjudicated group by group below; no cross-group '
    'excess-predictability headline is maintained.')
RESULTS = replace_paragraph(
    RESULTS, 'The figure below shows each group\'s weighted extensive-margin accuracy',
    'The corrected POSFIT-v3b numerical-adequacy gate is applied mechanically at '
    'the preregistered 0.25 threshold. Single women (85.7%, simulated 95% band '
    '[80.0%, 85.9%], ratio 0.096) and coupled women (89.8%, [88.1%, 91.2%], '
    'ratio 0.049) clear it and are reportable. Single men (ratio 0.361) and '
    'coupled men (ratio 0.353) are quadrature-limited, so their extensive '
    'accuracy is withheld. In particular, coupled men crossed the threshold after '
    'the corrected S11 evaluation and the earlier reportable classification is '
    'not preserved.')
RESULTS = replace_paragraph(
    RESULTS, 'The mean absolute deviation over all population moments is',
    'The corrected mean absolute deviation over all population moments is '
    '{{n:mae_singles|.4f}} across 36 single-adult moments and '
    '{{n:mae_couples|.4f}} across 30 couple moments. This correction is not an '
    'across-the-board fit improvement: singles MAE rises slightly, while couples '
    'MAE falls. The remaining common mismatch is underprediction of the observed '
    '37-hour mass point, by 3.8--6.5 percentage points across the four groups. '
    'That mass point lies outside the S11 structural full-time band '
    '$[37.5,40.5]$; it is not described as underprediction of that structural '
    'band. The sub-ten-hour cell remains a finite-integration-panel coverage '
    'limitation, and the long-hours reporting bin closes at 70 inclusive.')

_decomp = evidence.RESULTS.split('## The preliminary decomposition', 1)[1]
_decomp = clean_w1(_decomp)
_decomp = attach_decomp_caveat(_decomp)
_decomp = _decomp.replace(DECOMP_CAVEAT, DECOMP_CAVEAT + '\n\n' + SHORT_HOURS_LIMITATION, 1)
RESULTS += '\n\n## Preliminary restricted structural decomposition\n' + _decomp

SENSITIVITY = v6.SENSITIVITY
SENSITIVITY = replace_paragraph(
    SENSITIVITY, '**Single men\'s extensive-accuracy statistic is quadrature-limited.**',
    '**Men\'s extensive-accuracy statistics are quadrature-limited.** The '
    'corrected gate withholds the extensive-accuracy statistic for both single '
    'men and coupled men. The corrected population moments instead isolate '
    'underprediction of the observed 37-hour mass point, outside the S11 '
    'structural full-time band, at 5.2 percentage points for single men, 3.8 for '
    'single women, 4.4 for coupled men and 6.5 for coupled women. This correction '
    'is not an across-the-board fit improvement: singles MAE rises slightly, while '
    'couples MAE falls; the corrected values are {{n:mae_singles|.4f}} and '
    '{{n:mae_couples|.4f}}.')
SENSITIVITY = replace_paragraph(
    SENSITIVITY, '**Individual-level predictive diagnostics raise possible excess stochastic dispersion',
    '**Four-group corrected diagnostic adjudication.** On the weighted composite '
    'rule, the conditioning verdict is MECHANICAL_STOCHASTIC_CONDITIONING in all '
    'four groups. The excess-dispersion verdict is MISSPECIFICATION_EVIDENCE for '
    'coupled men and coupled women, and INCONCLUSIVE_QUADRATURE_LIMITED for single '
    'men and single women. Numerical adequacy of one displayed accuracy and the '
    'composite verdict are different gates. The earlier three-group '
    'excess-predictability claim is withdrawn; the corrected evidence is reported '
    'only through these four group-specific adjudications.')
SENSITIVITY += ('\n\n**Short-hours support.** ' + SHORT_HOURS_LIMITATION)
SENSITIVITY += r'''

**RUM-A/B estimation-input band defect.** The benchmark audit found that RUM-A's estimation input encoded the S12-native full employment-hours width, 26.5 rather than the S11 width 29.5, shifting its log average-hours-density input by the alternative-invariant constant -0.050856. That constant cancels from the conditional sampled-set likelihood, so the RUM-A estimates, standard errors, maximized criterion and criterion comparison are unchanged. RUM-B does not read those density rows. The stale RUM-A metadata and absolute opportunity-mass levels, and the old criterion-B reporting-bin moments for both benchmarks, were nevertheless defective: the corrected benchmark MAEs are {{n:mae_ruma|.4f}} and {{n:mae_rumb|.4f}}. No audited downstream level use was found, but the search was not exhaustive; absolute level uses of those inputs therefore remain a limitation.

**Numerically blocked opportunity-prospect metric.** ''' + WEA_STATUS + '\n'

CONCLUSION = clean_w1(v6.CONCLUSION)
CONCLUSION += ('\n\nThe main results therefore retain the computed preliminary restricted '
               'P/A/B exercise: earning opportunities contribute more than coarse '
               'geographic/temporal access within the declared game, with exact '
               'closure, second-seed reproduction, anchor-exclusion robustness '
               'and a preference contribution whose sign changes under '
               'equivalisation. ' + DECOMP_CAVEAT + '\n\n' + SHORT_HOURS_LIMITATION + '\n')

APP_DECOMP = clean_w1(v6.APP_DECOMP)
APP_DECOMP = attach_decomp_caveat(APP_DECOMP)
APP_DECOMP = APP_DECOMP.replace(DECOMP_CAVEAT,
                                DECOMP_CAVEAT + '\n\n' + SHORT_HOURS_LIMITATION, 1)

SECTIONS = []
for section in v6.SECTIONS:
    new = dict(section)
    replacement = {
        'intro': INTRO,
        'welfare': WELFARE,
        'results': RESULTS,
        'sensitivity': SENSITIVITY,
        'conclusion': CONCLUSION,
        'appdecomp': APP_DECOMP,
    }.get(section['key'])
    if replacement is not None:
        new['body'] = replacement
    else:
        new['body'] = clean_w1(new['body'])
    SECTIONS.append(new)

QA = [(q, clean_w1(a)) for q, a in v6.QA]
QA.extend([
    ('Which extensive-accuracy results survive the corrected gate?',
     'Single women and coupled women clear the corrected weighted numerical-adequacy '
     'gate. The corresponding statistics for single men and coupled men are '
     'quadrature-limited and withheld.'),
    ('What did the corrected hours comparison find?',
     'The common mismatch is underprediction of the observed 37-hour mass point by '
     '3.8--6.5 percentage points across groups. The point lies outside the S11 '
     'structural full-time band, so this is not a structural full-time-band claim.'),
    ('Is the ex-ante opportunity-prospect metric a result?',
     r'$W_{EA,\mathrm{flat}}$ is definition-only and numerically blocked. No number '
     'for that metric is reported.'),
])
