"""Generate LaTeX result macros from the shared numerical registry."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOR = json.loads((ROOT / "reports/numbers_of_record_v1.json").read_text(encoding="utf-8"))["entries"]
FD = json.loads((ROOT / "reports/research_story_build/final_descriptives_v1.json").read_text(encoding="utf-8"))
OUT = Path(__file__).with_name("JMP_working_paper_for_seminar_v2_numbers.tex")


def value(key: str) -> float:
    return float(NOR[key]["value"])


def comma(x: float) -> str:
    return f"{int(round(x)):,}"


def fixed(x: float, digits: int) -> str:
    return f"{x:.{digits}f}"


macros = {
    "NSingles": comma(FD["n_singles"]),
    "NCouples": comma(FD["n_couples"]),
    "MinHoursSingles": fixed(FD["minimum_employed_hours"]["singles"], 0),
    "MinHoursCoupleMen": fixed(FD["minimum_employed_hours"]["couple_men"], 0),
    "MinHoursCoupleWomen": fixed(FD["minimum_employed_hours"]["couple_women"], 0),
    "CurrentSingleGini": fixed(value("state_I00_female_raw"), 4),
    "CurrentSinglePrefShare": fixed(100 * value("C_pref_female_raw_share"), 1),
    "CurrentSingleEnvShare": fixed(100 * value("C_env_female_raw_share"), 1),
    "CurrentCoupleGini": fixed(value("couples_state_I0000_raw"), 4),
    "CurrentCouplePrefPoints": fixed(value("couples_C_P_raw"), 4),
    "CurrentCoupleEnvPoints": fixed(value("couples_C_E_raw"), 4),
    "SingleInterior": comma(value("n_params_interior")),
    "SingleBounds": comma(value("n_params_at_bound")),
    "CoupleFree": comma(value("n_couples_free")),
    "CoupleInterior": comma(value("n_couples_interior")),
    "CoupleBounds": comma(value("n_couples_at_bound")),
}

lines = [
    "% Generated by build_paper_v2_numbers.py from reports/numbers_of_record_v1.json",
    "% and reports/research_story_build/final_descriptives_v1.json. Do not edit values here.",
]
for name, val in macros.items():
    lines.append(rf"\newcommand{{\{name}}}{{{val}}}")
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(OUT)
