"""Machine-check the nine circulation gates in the two V7 rulings."""
from __future__ import annotations

import csv
import hashlib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WORKSPACE = ROOT.parent
POSFIT_REPO = WORKSPACE / "MNL_posfit"
MNL_REPO = WORKSPACE / "MNL"
BF = POSFIT_REPO / "outputs/band_fix_1"
PF = POSFIT_REPO / "outputs/positive_fit_diagnostics_v3b"
NC = POSFIT_REPO / "outputs/posfit_node_convergence_v3b"
MOM = (POSFIT_REPO / "experiments/JMP_SEMINAR_SPRINT/runs/"
       "bandfix2_recompute/new_results_v1.json")
OUT_JSON = ROOT / "reports/v7_ruling_gate_results.json"
OUT_MD = ROOT / "reports/v7_ruling_gate_results.md"

W1 = ("The empirical Mapping-F implementation evaluates the attained bundle "
      "against the universally available non-employment reference. Under the "
      "current specification, estimated opportunity density therefore affects "
      "this money metric through attained outcomes rather than through a direct "
      "opportunity-prospect term.")
DECOMP = ("This percentage is the change generated by the declared restricted "
          "P/A/B game. It is not an estimate of the total fraction of inequality "
          "caused by unequal job opportunities.")
SHORT = ("The preliminary attainment exercise is evaluated on the already-priced "
         "estimation panel. That panel sparsely represents the lower part of the "
         "structural hours support. A separate integration audit shows substantial "
         "structural mass in that region. The direct importance of this limitation "
         "for the current attained-bundle decomposition has not been fully quantified, "
         "so the result remains explicitly preliminary.")


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def normal(text: str) -> str:
    text = text.replace("\\_", "_").replace("\\%", "%")
    text = text.replace("--", "–")
    return re.sub(r"\s+", " ", text).strip()


def notebook_text(path: Path) -> str:
    nb = json.loads(read(path))
    chunks: list[str] = []
    for cell in nb.get("cells", []):
        chunks.append("".join(cell.get("source", [])))
        for output in cell.get("outputs", []):
            chunks.append("".join(output.get("text", [])))
            data = output.get("data", {})
            for kind in ("text/plain", "text/markdown", "text/html"):
                value = data.get(kind, "")
                chunks.append("".join(value) if isinstance(value, list) else value)
    return "\n".join(chunks)


SURFACE_PATHS = {
    "story_source": ROOT / "reports/research_story_build/story_v7.generated.md",
    "story_html": ROOT / "reports/JMP_research_story_report_v7.html",
    "gallery": ROOT / "reports/JMP_results_gallery_current.html",
    "paper": ROOT / "manuscript/JMP_working_paper_for_seminar_v7.tex",
    "paper_fit": ROOT / "manuscript/sections/05b_fit.tex",
    "deck": ROOT / "beamer/JMP_seminar_deck_r7.tex",
    "rehearsal_versioned": ROOT / "reports/rehearsal_pack_v7.md",
    "rehearsal_current": ROOT / "reports/rehearsal_pack_v1.md",
}


def add_gate(code: str, name: str, checks: list[tuple[bool, str]]) -> dict:
    failures = [message for ok, message in checks if not ok]
    return {"gate": code, "name": name, "status": "PASS" if not failures else "FAIL",
            "checks": len(checks), "failures": failures}


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    gates: list[dict] = []

    # G1: corrected view and specification labels/edges.
    ev = json.loads(read(BF / "evaluation_view_provenance_audit_v1.json"))
    g1 = [
        (ev.get("verdict") == "PASS", "evaluation-view provenance verdict is not PASS"),
        (ev.get("native_panel_band_definition", {}).get("label") == "S12/S8",
         "native definition is not S12/S8"),
        (ev.get("evaluation_model_band_definition", {}).get("label") == "S11/S10",
         "evaluation definition is not S11/S10"),
        (ev.get("evaluation_model_band_definition", {}).get("working_pt1") == [18.5, 21.5],
         "S11 PT1 edges differ"),
        (ev.get("evaluation_model_band_definition", {}).get("working_pt2") == [29.5, 30.5],
         "S11 PT2 edges differ"),
        (ev.get("evaluation_model_band_definition", {}).get("working_ft") == [37.5, 40.5],
         "S11 FT edges differ"),
    ]
    for panel in ev.get("panels", []):
        g1.extend([
            (panel.get("PASS") is True, f"{panel.get('panel')} panel view did not pass"),
            (panel.get("non_band_columns_bit_identical") is True,
             f"{panel.get('panel')} non-band columns differ"),
            (all(v.get("rebuilt_equals_S11_S10_rule_mismatches") == 0
                 for v in panel.get("band_rule_checks", {}).values()),
             f"{panel.get('panel')} corrected band rule has mismatches"),
        ])
    gates.append(add_gate("G1", "S11 evaluation uses S11/S10 indicators", g1))

    # G2: every required dependent output family exists in v3b.
    required = [
        PF / "participation_reliability.csv", PF / "hard_classification_metrics.csv",
        PF / "joint_hours_state_confusion_matrix.csv", PF / "intensive_margin_extended.csv",
        PF / "scores.csv", PF / "scores_with_mcse.csv", PF / "reliability.csv",
        PF / "outcome_conditioned_calibration.csv", PF / "model_simulated_bands.csv",
        PF / "g2_adequacy.csv", PF / "decision_rules_results.csv",
        PF / "figures/07_model_simulated_bands.png", PF / "figures/08_aggregate_confusion_matrices.png",
        NC / "convergence_table.csv", NC / "figures/node_convergence.png",
        BF / "artifact_hashes_v3b.csv", PF / "run_provenance.json",
    ]
    prov = json.loads(read(PF / "run_provenance.json"))
    g2 = [(p.is_file() and p.stat().st_size > 0, f"missing/empty: {p}") for p in required]
    g2.extend([
        (prov.get("band_fix_1") is True, "v3b provenance lacks band_fix_1"),
        (prov.get("no_reestimation") is True, "v3b unexpectedly re-estimated"),
        (prov.get("no_pricing") is True, "v3b unexpectedly repriced"),
    ])
    gates.append(add_gate("G2", "POSFIT-dependent objects regenerated", g2))

    # G3: population moments regenerated and expected corrected dimensions/values exist.
    new = json.loads(read(MOM))
    summaries = new.get("summaries", {})
    moments = new.get("moments", [])
    g3 = [
        (len(moments) == 138, f"expected 138 corrected moments, found {len(moments)}"),
        (summaries.get("SINGLES", {}).get("n_moments") == 36, "singles moment count != 36"),
        (summaries.get("COUPLES", {}).get("n_moments") == 30, "couples moment count != 30"),
        (abs(summaries.get("SINGLES", {}).get("mean_absolute_error", -1) - 0.013997497845981723) < 1e-15,
         "singles corrected MAE differs"),
        (abs(summaries.get("COUPLES", {}).get("mean_absolute_error", -1) - 0.011854418614696214) < 1e-15,
         "couples corrected MAE differs"),
        (sum(m.get("moment") == "hours::h_36_5_37_5" and m.get("model") in ("SINGLES", "COUPLES")
             for m in moments) == 4, "four primary 37-hour cells not found"),
        (sum(m.get("moment") == "hours::ft" and m.get("model") in ("SINGLES", "COUPLES")
             for m in moments) == 4, "four corrected structural FT cells not found"),
    ]
    gates.append(add_gate("G3", "Population-fit moments regenerated", g3))

    # G4: unchanged threshold, mechanical adequacy, and corrected four-group verdict.
    with (PF / "g2_adequacy.csv").open(newline="", encoding="utf-8") as handle:
        adequacy = list(csv.DictReader(handle))
    selected = {r["group"]: r for r in adequacy if r["weighting"] == "weighted"
                and r["scope"] == "all" and r["statistic"] == "extensive_accuracy"}
    expected_adequacy = {
        "couples_female": (True, 0.049080431005192354),
        "couples_male": (False, 0.35266875663723635),
        "singles_female": (True, 0.09605380600085617),
        "singles_male": (False, 0.3606670631213232),
    }
    g4: list[tuple[bool, str]] = [(set(selected) == set(expected_adequacy), "adequacy group set differs")]
    for group, (adequate, ratio) in expected_adequacy.items():
        row = selected.get(group, {})
        g4.extend([
            (row.get("adequate") == str(adequate), f"{group} adequacy status differs"),
            (abs(float(row.get("adequacy_ratio_mcse_to_sampling_sd", -1)) - ratio) < 1e-14,
             f"{group} adequacy ratio differs"),
            (abs(float(row.get("g2_threshold_0_25_sampling_sd", -1)) -
                 0.25 * float(row.get("simulated_sd", 0))) < 1e-14,
             f"{group} threshold is not the preregistered 0.25 rule"),
        ])
    with (PF / "decision_rules_results.csv").open(newline="", encoding="utf-8") as handle:
        decisions = {r["group"]: r for r in csv.DictReader(handle) if r["weighting"] == "weighted"}
    expected_e = {"couples_male": "MISSPECIFICATION_EVIDENCE",
                  "couples_female": "MISSPECIFICATION_EVIDENCE",
                  "singles_male": "INCONCLUSIVE_QUADRATURE_LIMITED",
                  "singles_female": "INCONCLUSIVE_QUADRATURE_LIMITED"}
    for group, verdict in expected_e.items():
        row = decisions.get(group, {})
        g4.extend([
            (row.get("d_final_verdict") == "MECHANICAL_STOCHASTIC_CONDITIONING",
             f"{group} D verdict differs"),
            (row.get("e_final_verdict") == verdict, f"{group} E verdict differs"),
        ])
    gates.append(add_gate("G4", "Adequacy and four-group adjudication rerun mechanically", g4))

    # Load reader-facing source surfaces once. Binary image payloads are irrelevant.
    surface_text = {name: read(path) for name, path in SURFACE_PATHS.items()}
    surface_text["notebook"] = notebook_text(
        MNL_REPO / "experiments/JMP_SEMINAR_SPRINT/JMP_canonical_AtoZ.ipynb")
    combined = "\n".join(surface_text.values())
    combined_n = normal(combined)

    # G5: retired claim removed and exact replacement/fit caveat present.
    retired = [r"(?<!\d)9\.48(?!\d)", r"(?<!\d)7\.21(?!\d)",
               r"9\.5\s+(?:percentage|percentage\\)\s+points",
               r"(?<!\d)0\.0129(?!\d)", r"(?<!\d)0\.0136(?!\d)",
               r"near[- ]full[- ]time[^\n]{0,80}underprediction"]
    g5 = [(re.search(pattern, combined, flags=re.I) is None, f"retired pattern remains: {pattern}")
          for pattern in retired]
    for name in ("story_source", "paper", "deck", "rehearsal_versioned", "gallery", "notebook"):
        text = normal(surface_text[name]).lower()
        g5.extend([
            ("underprediction of the observed 37-hour mass point" in text,
             f"{name} lacks exact 37-hour finding"),
            ("singles mae rises slightly" in text or "singles mae rises" in text,
             f"{name} does not disclose that singles MAE rises"),
        ])
    gates.append(add_gate("G5", "Near-FT claim retired and 37-hour finding installed", g5))

    # G6: DECOMP assets and input frames unchanged, no S12 edge dependency.
    decomp_audit = read(BF / "BAND_FIX_3_verification_audit_v1.md")
    g6 = [
        ("DECOMP-2 no-dependency (ruling s6): PASS" in decomp_audit,
         "DECOMP section-level verification is not PASS"),
        ("dependency on S12-native edge constants | none on the executed path" in decomp_audit,
         "DECOMP no-S12-dependency evidence absent"),
        ("frame hashes vs the DECOMP-2 pins" in decomp_audit and "match" in decomp_audit,
         "DECOMP frame-hash comparison absent"),
        ("coalition Ginis and Shapley assets" in decomp_audit and "blob-identical" in decomp_audit,
         "DECOMP output-hash comparison absent"),
    ]
    gates.append(add_gate("G6", "DECOMP-2 no-dependency verification", g6))

    # G7: all requested current/versioned surfaces exist and identify V7/r7/v3b.
    required_surfaces = list(SURFACE_PATHS.values()) + [
        ROOT / "manuscript/JMP_working_paper_for_seminar_v7.pdf",
        ROOT / "beamer/build/JMP_seminar_deck_r7.pdf",
        ROOT / "beamer/build/JMP_seminar_deck_r7_rehearsal.pdf",
        ROOT / "reports/numbers_of_record_v7.json",
        MNL_REPO / "experiments/JMP_SEMINAR_SPRINT/JMP_canonical_AtoZ.ipynb",
    ]
    g7 = [(p.is_file() and p.stat().st_size > 0, f"missing/empty surface: {p}")
          for p in required_surfaces]
    g7.extend([
        ("POSFIT v3b" in surface_text["story_source"], "story source lacks POSFIT v3b lineage"),
        ("POSFIT v3b" in surface_text["gallery"], "gallery lacks POSFIT v3b lineage"),
        ("POSFIT v3b" in surface_text["notebook"], "notebook lacks POSFIT v3b lineage"),
        ("V7" in surface_text["deck"] or "v7" in surface_text["deck"] or
         "r7" in surface_text["deck"], "deck lacks V7/r7 identifier"),
    ])
    gates.append(add_gate("G7", "All seminar-facing surfaces rebuilt", g7))

    # G8: stale current structural definitions, retired figures, and v3 stamps are gone.
    structural_stale = [
        r"Part-time lower,?\s*\[17\.5,\s*21\.5\)",
        r"Part-time upper,?\s*\[28\.5,\s*30\.5\)",
        r"Full-time upper,?\s*\[36\.5,\s*40\.5\]",
        r"residual hours set of total width 26\.5",
    ]
    g8 = [(re.search(pattern, combined, flags=re.I) is None,
           f"stale structural label remains: {pattern}") for pattern in structural_stale]
    g8.extend([
        ("POSFIT v3, <code>" not in surface_text["gallery"], "gallery retains a v3 source stamp"),
        ("commit <code>96693269</code>" not in surface_text["gallery"],
         "gallery retains the superseded POSFIT commit stamp"),
        ("positive_fit_diagnostics_v3/figures" not in combined.replace("v3b/", ""),
         "current surface references a superseded v3 figure directory"),
        ("figV06" not in combined, "current surface retains a v6 fit figure identifier"),
        ("[18.5, 21.5)" in combined and "[29.5, 30.5)" in combined and
         "[37.5, 40.5]" in combined, "correct S11 structural labels are incomplete"),
    ])
    gates.append(add_gate("G8", "Stale text and rendered assets removed", g8))

    # G9: exact prior-ruling language, definition-only WEA, abstract rule, and withdrawal.
    story_n = normal(surface_text["story_source"])
    abstract = story_n.split("# 1.", 1)[0]
    g9 = [
        (normal(W1) in story_n, "exact W1_F wording absent from report source"),
        (normal(DECOMP) in story_n, "exact restricted-game caveat absent"),
        (normal(SHORT) in story_n, "exact short-hours limitation absent"),
        ("W_EA" in combined or "W_{EA" in combined, "WEA definition/status is absent"),
        ("definition-only" in combined_n.lower() or "definition has been fixed" in combined_n.lower(),
         "WEA is not identified as definition-only/fixed"),
        ("260" in combined and "block" in combined_n.lower(), "260-couple blocker is absent"),
        (re.search(r"W1[-–]EA.{0,80}\d+(?:\.\d+)?\s*%", combined_n, flags=re.I) is None,
         "a historical W1-EA percentage is live"),
        ("1.8" not in abstract and "9.9" not in abstract,
         "abstract contains the prohibited DECOMP magnitude"),
        ("earning-opportunity channel has a larger Shapley contribution" in abstract,
         "abstract lacks the qualitative decomposition ordering"),
        ("three-group excess-predictability claim is withdrawn" in combined_n.lower(),
         "three-group claim is not explicitly withdrawn"),
        ("RUM-A/B estimation-input band defect" in surface_text["story_source"],
         "RUM-A/B input defect is not disclosed"),
    ]
    gates.append(add_gate("G9", "W1_F, DECOMP-2, WEA, and limitations wording", g9))

    result = {
        "release": "V7-BUILD",
        "status": "PASS" if all(g["status"] == "PASS" for g in gates) else "FAIL",
        "gates": gates,
        "surface_sha256": {name: sha(path) for name, path in SURFACE_PATHS.items()},
    }
    OUT_JSON.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    lines = ["# V7 ruling gate results", "", f"Overall: **{result['status']}**", "",
             "| Gate | Requirement | Status | Checks |", "|---|---|---:|---:|"]
    for gate in gates:
        lines.append(f"| {gate['gate']} | {gate['name']} | **{gate['status']}** | {gate['checks']} |")
    failures = [(g["gate"], f) for g in gates for f in g["failures"]]
    if failures:
        lines.extend(["", "## Failures", ""] + [f"- {g}: {f}" for g, f in failures])
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    for gate in gates:
        print(f"{gate['gate']} {gate['status']}: {gate['name']} ({gate['checks']} checks)")
        for failure in gate["failures"]:
            print(f"  - {failure}")
    print("OVERALL", result["status"])
    return 0 if result["status"] == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
